package userInterface;

import java.awt.event.MouseEvent;
import listeners.CanvasListener;
import listeners.ToolListener;
/**
 *
 * @author Elias
 */
public class PanelTest extends javax.swing.JPanel implements ToolListener{

    /**
     * Creates new form PanelTest
     */
    public PanelTest() {            
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void toolSelected(String type) {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
